export type ColumnName = "notes" 
    | "label" 
    | "value" 
    | "status_id" 
    | "priority_id"
    | "category_id"
    | "clientType_id"
    | "due_date"
    | "order_date"
    | "estimated_arrival"
